#-----------------------------------------------------------------------------
# $Id: Makefile,v 1.1 2003/06/03 09:51:02 reid Exp $

TOP = ..
include $(TOP)/mk/boilerplate.mk

SGML_DOC = HSWin32

include $(TOP)/mk/target.mk
